---
- name: Generate nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "/home/ubuntu/default.conf"
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0644'
    force: yes



      #stopped

      #docker create --network=site --publish 80:80 --name nginx \
      #      -v website:/var/www/html \
      #      -v conf:/etc/nginx/conf.d/ \
      #      nginx:1.19.10-alpine
      #
      #docker cp default.conf nginx:/etc/nginx/conf.d/
      #
      #docker start nginx


- name: Create and start db services
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: nginx
    image: nginx:1.19.10-alpine
    volumes:
      - website:/var/www/html
      - /home/ubuntu:/etc/nginx/conf.d
    state: started
    recreate: no
    restart: no
    restart_policy: unless-stopped
    networks:
      - name: "{{ website_network }}"
    network_mode: "{{ website_network }}"
    ports:
      - "80:80"
    env:
      MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
      MYSQL_USER: '{{ mysql_user }}'
      MYSQL_PASSWORD: '{{ mysql_password }}'
      MYSQL_DATABASE: '{{ mysql_db }}'

