---
- name: Commons
  tags: commons
  gather_facts: no
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: common

- name: Swarm
  tags: swarm
  gather_facts: no
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: swarm

- name: Network
  tags: network
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: '{{ website_network }}'

- name: Volumes
  tags: volumes
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  become: yes
  become_method: sudo
  roles:
    - role: volumes

- name: Database
  tags: db
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  become: yes
  become_method: sudo
  roles:
    - role: db

- name: WordPress
  tags: wordpress
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  become: yes
  become_method: sudo
  roles:
    - role: wordpress

- name: PhpMyAdmin
  tags: phpmyadmin
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  become: yes
  become_method: sudo
  roles:
    - role: phpmyadmin

