---
- name: Commons
  tags: commons
  gather_facts: no
  hosts: all
  roles:
    - role: common

- name: Network
  tags: network
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: '{{ website_network }}'

- name: Volumes
  tags: volumes
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  tasks:
    - name: Create volumes
      community.docker.docker_volume:
        name: "{{ item }}"
        recreate: options-changed
      loop: "{{ volumes }}"

- name: Database
  tags: db
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  roles:
    - role: db

- name: Wordpress
  tags: wordpress
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  roles:
    - role: wordpress

- name: Phpmyadmin
  tags: phpmyadmin
  gather_facts: no
  hosts: "{{ groups['website'][0] }}"
  roles:
    - role: phpmyadmin
