---
- name: Create build directory
  file:
    path: /root/wp_dockerfile
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Template Wordpress dockerfile to /root/wp_dockerfile
  ansible.builtin.template:
    src: 'Dockerfile.j2'
    dest: '/root/wp_dockerfile/Dockerfile'
    owner: root
    group: root
    mode: '0644'

- name: Build wp container image
  docker_image:
    name: 'wp-cloud1:v0.1'
    build:
      path: '/root/wp_dockerfile'
      source: build
    state: present
