---
- name: Create build directory
  file:
    path: '{{ wp_build_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Template Wordpress dockerfile to /root/wp_dockerfile
  ansible.builtin.template:
    src: 'Dockerfile.j2'
    dest: '{{ wp_build_dir }}/Dockerfile'
    owner: root
    group: root
    mode: '0644'

- name: Build wp container image
  docker_image:
    name: '{{ wp_build }}'
    build:
      path: '/root/wp_dockerfile'
      source: build
    state: present
