---

#docker run -d --name wordpress \
#	-v website:/var/www/html \
#	--network=site \
#	-e WORDPRESS_DB_HOST=mariadb:3306 \
#	-e WORDPRESS_DB_USER=wordpress \
#	-e WORDPRESS_DB_PASSWORD=password \
#	-e MYSQL_DATABASE=wordpress \
#	-d wordpress:5.7.1-fpm-alpine

- name: Create and start Wordpress services
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: wordpress
    image: wordpress:5.7.1-fpm-alpine
    volumes:
      - website:/var/www/html
    state: started
    recreate: no
    restart: no
    restart_policy: unless-stopped
    networks:
      - name: "{{ website_network }}"
    network_mode: "{{ website_network }}"
    env:
      WORDPRESS_DB_HOST: 'mariadb:3306'
      WORDPRESS_DB_USER: '{{ mysql_user }}'
      WORDPRESS_DB_PASSWORD: '{{ mysql_password }}'
      MYSQL_DATABASE: '{{ mysql_db }}'
        #      WORDPRESS_DB_NAME: 'wordpress'
        #      MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
        #      MYSQL_USER: '{{ mysql_user }}'
        #      MYSQL_PASSWORD: '{{ mysql_password }}'
