---

#docker run -d --name wordpress \
#	-v website:/var/www/html \
#	--network=site \
#	-e WORDPRESS_DB_HOST=mariadb:3306 \
#	-e WORDPRESS_DB_USER=wordpress \
#	-e WORDPRESS_DB_PASSWORD=password \
#	-e MYSQL_DATABASE=wordpress \
#	-d wordpress:5.7.1-fpm-alpine

# Wordpress
- name: Create and start Wordpress services
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: '{{ wp_name }}'
    image: '{{ wp_image }}'
    volumes:
      - "{{ wp_volume }}:/var/www/html"
    state: started
    recreate: no
    restart: no
    restart_policy: unless-stopped
    networks:
      - name: "{{ website_network }}"
    network_mode: "{{ website_network }}"
    ports: '{{ wp_ports }}'
    env: '{{ wp_env }}'
