---
# Phpmyadmin
- name: Create and start phpmyadmin services
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: '{{ pma_name }}'
    image: '{{ pma_image }}'
    state: started
    recreate: no
    restart: no
    restart_policy: unless-stopped
    networks:
      - name: "{{ website_network }}"
    network_mode: "{{ website_network }}"
    ports: '{{ pma_ports }}'
    env: '{{ pma_env }}'
