---

#docker run -d --network site -v db:/var/lib/mysql --name mysql \
#	-e MYSQL_ROOT_PASSWORD=plussimple \
#	-e MYSQL_USER=wordpress \
#	-e MYSQL_PASSWORD=password \
#	-e MYSQL_DATABASE=wordpress \
#	mysql:5.7

- name: Create and start db services
  community.docker.docker_swarm_service:
    name: '{{ db_name }}'
    image: '{{ db_image }}'
    replicas: 2
    placement:
      replicas_max_per_node: 2
    labels:
      abarthel.dev.app: "cloud-1"
      abarthel.dev.description: "Wordpress website deployment - a 42 project"
    env: '{{ db_env }}'
    restart_config:
      condition: 'on-failure'
      delay: '5s'
      max_attempts: 3
    networks:
      - name: "{{ website_network }}"
    update_config:
      failure_action: 'rollback'
    rollback_config:
      parallelism: 2
      delay: '1m'
      order: 'stop-first'
    mounts:
      - source: '{{ db_volume }}'
        type: 'volume'
        no_copy: 'yes'
        target: '/var/lib/mysql'
