---
- name: Create db volume directory
  file:
    path: '{{ db_volume }}'
    state: directory
    recurse: yes
    mode: '0755'
    owner: '{{ user }}'
    group: '{{ group }}'

- name: Generate Docker-compose manifest
  template:
    src: "docker-compose.yaml.j2"
    dest: "{{ db_dir }}/docker-compose.yaml"
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0644'

- name: Deploy database container
  shell: "MYSQL_ROOT_PASSWORD={{ mysql_root_password }} MYSQL_USER={{ mysql_user }} MYSQL_PASSWORD={{ mysql_password }} MYSQL_DATABASE={{ mysql_db }} docker-compose up"
  args:
    chdir: '{{ db_dir }}'
    executable: /bin/bash
