---
- name: Create and start db services
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: db
    image: mysql:{{ mysql_version }}
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    state: started
    recreate: no
    restart: no
    restart_policy: unless-stopped
    networks:
      - name: "{{ website_network }}"
    network_mode: "{{ website_network }}"
    env:
      MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
      MYSQL_USER: '{{ mysql_user }}'
      MYSQL_PASSWORD: '{{ mysql_password }}'
      MYSQL_DATABASE: '{{ mysql_db }}'
