---

#docker run -d --network site -v db:/var/lib/mysql --name mysql \
#	-e MYSQL_ROOT_PASSWORD=plussimple \
#	-e MYSQL_USER=wordpress \
#	-e MYSQL_PASSWORD=password \
#	-e MYSQL_DATABASE=wordpress \
#	mysql:5.7

- name: Create and start db services
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: '{{ db_name }}'
    image: '{{ db_image }}'
    volumes:
      - '{{ db_volume }}:/var/lib/mysql'
    state: started
    recreate: no
    restart: no
    restart_policy: unless-stopped
    networks:
      - name: "{{ website_network }}"
    network_mode: "{{ website_network }}"
    env: '{{ db_env }}'
      #    env:
      #      MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
      #      MYSQL_USER: '{{ mysql_user }}'
      #      MYSQL_PASSWORD: '{{ mysql_password }}'
      #      MYSQL_DATABASE: '{{ mysql_db }}'
