---
- name: Check boot swap configuration
  slurp:
    src:  /etc/crontab
  register: crontab

- name: Disable Swap
  script: swapoff.sh
  when: "'swapoff -a' not in crontab.content|b64decode"

- name: Load Kernel Parameters
  shell: sysctl --system
  when: "'swapoff -a' not in crontab.content|b64decode"

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
